<div class="jumbotron">
    <h1><?php echo $this->translate('One Commit Per Day'); ?></h1>
    <p><?php echo $this->translate('As simple as the title, join others who also are committed to doing at least one commmit to a github repo every day. An easy way to stay active and help drive us to contribute more.'); ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank"><?php echo $this->translate('Accept The Challenge') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Daily Reminders') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Receive daily motivational reminders to do a commit every day. The result is a friendly email each day to spur you along and help get yourself in gear to contribute in some way.'); ?></p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('Get Daily Reminders') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Friendly Stats') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('This site will contain keep your status, and let others see how your doing as well as let you see how others are doing. Because community is the best motivation. If you notice someone has fallen off the wagon, help them get back up.'); ?></p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Awards Board') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('See the top contributors, longest running contributors, and learn good habits from those doing it daily.') ?></p>
                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
